services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
    env_file:
      - ./.env
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 web_cv_amirbenitez.wsgi:application
    volumes:
      - .:/code
      - media_volume:/code/media/
      - static_volume:/code/staticfiles/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    links:
      - db:db

volumes:
  postgres_data:
  static_volume:
  media_volume: