# Generated by Django 3.2.25 on 2024-05-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20240511_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='appstore_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='google_play_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/portfolio/carousel_images/')),
                ('projectContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.projectcontent')),
            ],
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contents', to='portfolio.project'),
        ),
    ]
