# Generated by Django 3.2.25 on 2024-07-20 16:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20240517_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcontent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
