# Generated by Django 3.2.25 on 2024-07-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_projectcontent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='projectcontentimage',
            name='image',
            field=models.ImageField(upload_to='portfolio/carousel_images/'),
        ),
    ]
