# Generated by Django 3.2.25 on 2024-04-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('nacionality', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'My personal data',
            },
        ),
    ]
