# Generated by Django 3.2.25 on 2024-05-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_skill_main_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile/'),
        ),
    ]
