# Generated by Django 3.2.25 on 2024-05-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_rename_profilepicture_personaldata_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
