# Generated by Django 3.2.25 on 2024-05-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20240502_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='short_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
