# Generated by Django 3.2.25 on 2024-05-09 00:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_personaldata_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
